[2024-09-03T08:06:45.955+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-03T08:06:45.968+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ingestion.save_data manual__2024-09-03T08:06:41.565368+00:00 [queued]>
[2024-09-03T08:06:45.973+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ingestion.save_data manual__2024-09-03T08:06:41.565368+00:00 [queued]>
[2024-09-03T08:06:45.974+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2024-09-03T08:06:45.984+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): save_data> on 2024-09-03 08:06:41.565368+00:00
[2024-09-03T08:06:45.991+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1732) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-03T08:06:45.992+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ingestion', 'save_data', 'manual__2024-09-03T08:06:41.565368+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag2.py', '--cfg-path', '/tmp/tmp8n9kn7fh']
[2024-09-03T08:06:45.992+0000] {standard_task_runner.py:72} INFO - Started process 1734 to run task
[2024-09-03T08:06:45.993+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask save_data
[2024-09-03T08:06:46.023+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_ingestion.save_data manual__2024-09-03T08:06:41.565368+00:00 [running]> on host 670a75e9450f
[2024-09-03T08:06:46.094+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_ingestion' AIRFLOW_CTX_TASK_ID='save_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-03T08:06:41.565368+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-03T08:06:41.565368+00:00'
[2024-09-03T08:06:46.095+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-03T08:06:46.096+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-03T08:06:46.096+0000] {logging_mixin.py:190} INFO - Current task name:save_data state:running start_date:2024-09-03 08:06:45.968478+00:00
[2024-09-03T08:06:46.096+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_ingestion and current dag run status:running
[2024-09-03T08:06:46.096+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-03T08:06:46.097+0000] {logging_mixin.py:190} INFO - Data received: []
[2024-09-03T08:06:46.097+0000] {logging_mixin.py:190} INFO - No data to save.
[2024-09-03T08:06:46.098+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-03T08:06:46.105+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-03T08:06:46.105+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_data_ingestion, task_id=save_data, run_id=manual__2024-09-03T08:06:41.565368+00:00, execution_date=20240903T080641, start_date=20240903T080645, end_date=20240903T080646
[2024-09-03T08:06:46.113+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-09-03T08:06:46.113+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-09-03T08:06:46.114+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_ingestion queued_at:2024-09-03 08:06:41.572513+00:00
[2024-09-03T08:06:46.114+0000] {logging_mixin.py:190} INFO - Task hostname:670a75e9450f operator:PythonOperator
[2024-09-03T08:06:46.126+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-09-03T08:06:46.138+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-03T08:06:46.140+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
