[2024-09-12T22:29:23.245+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-12T22:29:23.255+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:29:21.560059+00:00 [queued]>
[2024-09-12T22:29:23.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:29:21.560059+00:00 [queued]>
[2024-09-12T22:29:23.262+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-12T22:29:23.271+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-09-12 22:29:21.560059+00:00
[2024-09-12T22:29:23.278+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2012) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T22:29:23.278+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'call_api_task', 'manual__2024-09-12T22:29:21.560059+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmp1dw8k2ct']
[2024-09-12T22:29:23.279+0000] {standard_task_runner.py:63} INFO - Started process 2014 to run task
[2024-09-12T22:29:23.279+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask call_api_task
[2024-09-12T22:29:23.311+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:29:21.560059+00:00 [running]> on host 1ab47b72986b
[2024-09-12T22:29:23.376+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T22:29:21.560059+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T22:29:21.560059+00:00'
[2024-09-12T22:29:23.377+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-12T22:29:23.391+0000] {base.py:84} INFO - Using connection ID 'ingestion_api' for task execution.
[2024-09-12T22:29:23.572+0000] {logging_mixin.py:188} INFO - DataFrame saved to PostgreSQL successfully.
[2024-09-12T22:29:23.576+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T22:29:23.580+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-09-12T22:29:24.011+0000] {logging_mixin.py:188} INFO - File uploaded to weather_bucket_it_skolan/weather_data.csv
[2024-09-12T22:29:24.012+0000] {python.py:237} INFO - Done. Returned value was:    clouds    datetime  dewpt  ...  wind_dir  wind_gust_spd  wind_spd
0      50  2024-09-09   12.3  ...       123           12.4       6.1
1      50  2024-09-10   12.4  ...       172           13.2       4.9
2      65  2024-09-11   11.7  ...       173           12.8       4.1

[3 rows x 35 columns]
[2024-09-12T22:29:24.037+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-12T22:29:24.064+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_python_operator_hook, task_id=call_api_task, run_id=manual__2024-09-12T22:29:21.560059+00:00, execution_date=20240912T222921, start_date=20240912T222923, end_date=20240912T222924
[2024-09-12T22:29:24.094+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-12T22:29:24.107+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-12T22:29:24.109+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
