[2024-09-12T22:45:09.413+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-12T22:45:09.425+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:08.505480+00:00 [queued]>
[2024-09-12T22:45:09.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:08.505480+00:00 [queued]>
[2024-09-12T22:45:09.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-12T22:45:09.441+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): call_api_task> on 2024-09-12 22:45:08.505480+00:00
[2024-09-12T22:45:09.447+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator_hook', 'call_api_task', 'manual__2024-09-12T22:45:08.505480+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/example_python_operator_hook.py', '--cfg-path', '/tmp/tmpzg81e0fy']
[2024-09-12T22:45:09.448+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2482) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-12T22:45:09.448+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask call_api_task
[2024-09-12T22:45:09.449+0000] {standard_task_runner.py:63} INFO - Started process 2484 to run task
[2024-09-12T22:45:09.476+0000] {task_command.py:426} INFO - Running <TaskInstance: example_python_operator_hook.call_api_task manual__2024-09-12T22:45:08.505480+00:00 [running]> on host 1ab47b72986b
[2024-09-12T22:45:09.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_python_operator_hook' AIRFLOW_CTX_TASK_ID='call_api_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T22:45:08.505480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-12T22:45:08.505480+00:00'
[2024-09-12T22:45:09.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-12T22:45:09.559+0000] {base.py:84} INFO - Using connection ID 'ingestion_api' for task execution.
[2024-09-12T22:45:09.747+0000] {logging_mixin.py:188} INFO - DataFrame saved to PostgreSQL successfully.
[2024-09-12T22:45:09.751+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-09-12T22:45:09.755+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-09-12T22:45:09.802+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/google/cloud/bigquery/_pandas_helpers.py:537 UserWarning: Pyarrow could not determine the type of columns: snow_depth.
[2024-09-12T22:45:14.558+0000] {logging_mixin.py:188} INFO - DataFrame uploaded to BigQuery table: pacific-ethos-433305-u0.The_Weather_Data.The_Weather_Table
[2024-09-12T22:45:14.558+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-12T22:45:14.559+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-12T22:45:14.565+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_python_operator_hook, task_id=call_api_task, run_id=manual__2024-09-12T22:45:08.505480+00:00, execution_date=20240912T224508, start_date=20240912T224509, end_date=20240912T224514
[2024-09-12T22:45:14.581+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-12T22:45:14.591+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-12T22:45:14.593+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
